/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeemanager.gui;

import employeemanager.newEmployee.Employee;
import employeemanager.service.EmployeeService;
import static employeemanager.service.EmployeeService.EmployeeDao;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Main extends javax.swing.JFrame {

    private final int ID = 0;

    //add edit employee methods
    //делаем пустые методы
    //добавить в employeeservice method который показывает все обьекты аррай листа в виде кнопки принт которая из empoyee service показывает все 
    public static void addEmployee(Employee emp) {
        try {
            if (emp.isValid()) {
                addEmployeeToList(emp);
            } else {
                //display error
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }

    public static void editEmployee(int idEmployee, String newName, String newSurname, String birth, String newStreet, String newCity, String newCountry, String newZip, String newPosition) {
        DefaultTableModel employeeListModel = (DefaultTableModel) Main.employeeTable.getModel();
        employeeListModel.setValueAt(newName, idEmployee - 1, 1); // тут мы определяем куда будем кидать новую 1) новая инфа 2)на какую строчку 3)какой столбец
        employeeListModel.setValueAt(newSurname, idEmployee - 1, 2);
        employeeListModel.setValueAt(birth, idEmployee - 1, 3);
        employeeListModel.setValueAt(newStreet + " " + newCity + " " + newCountry + " " + newZip, idEmployee - 1, 4);
        employeeListModel.setValueAt(newPosition, idEmployee - 1, 5);
        //вызвать employee service
        EmployeeService.edit(idEmployee, newName, newSurname, birth, newStreet, newCity, newCountry, newZip, newPosition);
    }

    /**
     * Creates new form MainWindow
     */
    public Main() {
        initComponents();
        this.loadEmployees();

    }

    private void loadEmployees() {
//        ArrayList<Employee> empDao = EmployeeService.getAll();
////        EmployeeService.getAll();
//        DefaultTableModel employeeListModel = (DefaultTableModel) Main.employeeTable.getModel();
//        for (Employee emp : empDao) {
//            int employeeID = employeeListModel.getRowCount() + 1;
//            employeeListModel.addRow(new Object[]{employeeID, emp.getName(), emp.getSurname(), emp.getBirth(), emp.getStreet() + " " + emp.getCity() + " " + emp.getCountry() + " " + String.valueOf(emp.getZip()), emp.getPosition().toString()});
//        }
    }

    private static void addEmployeeToList(Employee emp) throws SQLException {
        DefaultTableModel employeeListModel = (DefaultTableModel) Main.employeeTable.getModel(); //так ссылаемся на наши данные которые мы указываем в таблице
        int employeeID = employeeListModel.getRowCount() + 1;
        employeeListModel.addRow(new Object[]{employeeID, emp.getName(), emp.getSurname(), emp.getBirth(), emp.getStreet() + " " + emp.getCity() + " " + emp.getCountry() + " " + String.valueOf(emp.getZip()), emp.getPosition().toString()});
        emp.setId(employeeID);
        EmployeeService.add(emp);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        btnPrint = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        exportBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");
        setLocation(new java.awt.Point(150, 150));

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Surname", "Birth Date", "Adress", "Profession"
            }
        ));
        jScrollPane1.setViewportView(employeeTable);
        if (employeeTable.getColumnModel().getColumnCount() > 0) {
            employeeTable.getColumnModel().getColumn(0).setMinWidth(30);
            employeeTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            employeeTable.getColumnModel().getColumn(0).setMaxWidth(30);
            employeeTable.getColumnModel().getColumn(1).setMinWidth(150);
            employeeTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            employeeTable.getColumnModel().getColumn(1).setMaxWidth(150);
            employeeTable.getColumnModel().getColumn(2).setMinWidth(150);
            employeeTable.getColumnModel().getColumn(2).setPreferredWidth(150);
            employeeTable.getColumnModel().getColumn(2).setMaxWidth(150);
            employeeTable.getColumnModel().getColumn(3).setMinWidth(100);
            employeeTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            employeeTable.getColumnModel().getColumn(3).setMaxWidth(100);
            employeeTable.getColumnModel().getColumn(5).setMinWidth(150);
            employeeTable.getColumnModel().getColumn(5).setPreferredWidth(150);
            employeeTable.getColumnModel().getColumn(5).setMaxWidth(150);
        }

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        exportBtn.setText("EXPORT");
        exportBtn.setPreferredSize(new java.awt.Dimension(66, 32));
        exportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(exportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrint)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnPrint))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        Add addWindow = new Add();
        addWindow.setVisible(true);


    }//GEN-LAST:event_addActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        EmployeeService.printAllEmployees();
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int selectedRow = Main.employeeTable.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel employeeListModel = (DefaultTableModel) Main.employeeTable.getModel();
            //Employee employeeToEdit = null;
            Object value = employeeListModel.getValueAt(selectedRow, ID).toString();
            Integer employeeID = Integer.parseInt(value.toString());
            Employee foundEmployee = EmployeeService.getByID(employeeID);
            Edit editWindow = new Edit(foundEmployee);
            editWindow.setVisible(true);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = Main.employeeTable.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel employeeListModel = (DefaultTableModel) Main.employeeTable.getModel();
            Object value = employeeListModel.getValueAt(selectedRow, ID).toString();
            Integer employeeID = Integer.parseInt(value.toString());
            employeeListModel.removeRow(selectedRow);
            EmployeeService.delete(employeeID);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void exportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportBtnActionPerformed
        Export exportWindow = new Export();
        exportWindow.setVisible(true);
    }//GEN-LAST:event_exportBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JToggleButton btnPrint;
    public static javax.swing.JTable employeeTable;
    private javax.swing.JToggleButton exportBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
